#pragma once

// Name: Squad, Version: 13-01-2021


#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

/*!!HELPER_DEF!!*/

/*!!DEFINE!!*/

namespace UFT
{
//---------------------------------------------------------------------------
// Enums
//---------------------------------------------------------------------------

// Enum Spectral.ESpectralLedName
enum class ESpectralLedName : uint8_t
{
	Invalid                        = 0,
	Backspace                      = 1,
	Tab                            = 2,
	Enter                          = 3,
	Pause                          = 4,
	CapsLock                       = 5,
	Escape                         = 6,
	Spacebar                       = 7,
	PageUp                         = 8,
	PageDown                       = 9,
	End                            = 10,
	Home                           = 11,
	LeftArrow                      = 12,
	UpArrow                        = 13,
	RightArrow                     = 14,
	DownArrow                      = 15,
	PrintScreen                    = 16,
	Insert                         = 17,
	Delete                         = 18,
	Zero                           = 19,
	One                            = 20,
	Two                            = 21,
	Three                          = 22,
	Four                           = 23,
	Five                           = 24,
	Six                            = 25,
	Seven                          = 26,
	Eight                          = 27,
	Nine                           = 28,
	A                              = 29,
	B                              = 30,
	C                              = 31,
	D                              = 32,
	E                              = 33,
	F                              = 34,
	G                              = 35,
	H                              = 36,
	I                              = 37,
	J                              = 38,
	K                              = 39,
	L                              = 40,
	M                              = 41,
	N                              = 42,
	O                              = 43,
	P                              = 44,
	Q                              = 45,
	R                              = 46,
	S                              = 47,
	T                              = 48,
	U                              = 49,
	V                              = 50,
	W                              = 51,
	X                              = 52,
	Y                              = 53,
	Z                              = 54,
	LeftWindows                    = 55,
	RightWindows                   = 56,
	Applications                   = 57,
	Numpad0                        = 58,
	Numpad1                        = 59,
	Numpad2                        = 60,
	Numpad3                        = 61,
	Numpad4                        = 62,
	Numpad5                        = 63,
	Numpad6                        = 64,
	Numpad7                        = 65,
	Numpad8                        = 66,
	Numpad9                        = 67,
	Multiply                       = 68,
	Add                            = 69,
	Subtract                       = 70,
	Decimal                        = 71,
	Divide                         = 72,
	F1                             = 73,
	F2                             = 74,
	F3                             = 75,
	F4                             = 76,
	F5                             = 77,
	F6                             = 78,
	F7                             = 79,
	F8                             = 80,
	F9                             = 81,
	F10                            = 82,
	F11                            = 83,
	F12                            = 84,
	NumLock                        = 85,
	ScrollLock                     = 86,
	LeftShift                      = 87,
	RightShift                     = 88,
	LeftControl                    = 89,
	RightControl                   = 90,
	Semicolon                      = 91,
	Plus                           = 92,
	Comma                          = 93,
	Minus                          = 94,
	Period                         = 95,
	Slash                          = 96,
	Tilde                          = 97,
	LeftBracket                    = 98,
	Backslash                      = 99,
	RightBracket                   = 100,
	Quote                          = 101,
	LeftAlt                        = 102,
	RightAlt                       = 103,
	NumpadEnter                    = 104,
	G1                             = 105,
	G2                             = 106,
	G3                             = 107,
	G4                             = 108,
	G5                             = 109,
	G6                             = 110,
	G7                             = 111,
	G8                             = 112,
	G9                             = 113,
	Logo                           = 114,
	Badge                          = 115,
	NonUsBackslash                 = 116,
	Lang1                          = 117,
	Lang2                          = 118,
	LedProgramming                 = 119,
	Brightness                     = 120,
	NonUsTilde                     = 121,
	WindowsLock                    = 122,
	Mute                           = 123,
	Stop                           = 124,
	PreviousTrack                  = 125,
	PlayPause                      = 126,
	NextTrack                      = 127,
	VolumeUp                       = 128,
	VolumeDown                     = 129,
	MR                             = 130,
	M1                             = 131,
	M2                             = 132,
	M3                             = 133,
	G10                            = 134,
	G11                            = 135,
	G12                            = 136,
	G13                            = 137,
	G14                            = 138,
	G15                            = 139,
	G16                            = 140,
	G17                            = 141,
	G18                            = 142,
	Fn                             = 143,
	International1                 = 144,
	International2                 = 145,
	International3                 = 146,
	International4                 = 147,
	International5                 = 148,
	International6                 = 149,
	International7                 = 150,
	KeyboardZone1                  = 151,
	KeyboardZone2                  = 152,
	KeyboardZone3                  = 153,
	KeyboardZone4                  = 154,
	KeyboardZone5                  = 155,
	KeyboardZone6                  = 156,
	KeyboardZone7                  = 157,
	KeyboardZone8                  = 158,
	KeyboardZone9                  = 159,
	KeyboardZone10                 = 160,
	KeyboardZone11                 = 161,
	KeyboardZone12                 = 162,
	KeyboardZone13                 = 163,
	KeyboardZone14                 = 164,
	KeyboardZone15                 = 165,
	KeyboardZone16                 = 166,
	KeyboardZone17                 = 167,
	KeyboardZone18                 = 168,
	KeyboardZone19                 = 169,
	MouseZone1                     = 170,
	MouseZone2                     = 171,
	MouseZone3                     = 172,
	MouseZone4                     = 173,
	MouseZone5                     = 174,
	MouseZone6                     = 175,
	MouseZone7                     = 176,
	MouseZone8                     = 177,
	MouseZone9                     = 178,
	MouseZone10                    = 179,
	MouseZone11                    = 180,
	MouseZone12                    = 181,
	MouseZone13                    = 182,
	MouseZone14                    = 183,
	MouseZone15                    = 184,
	MouseZone16                    = 185,
	MouseZone17                    = 186,
	MouseZone18                    = 187,
	MouseZone19                    = 188,
	MouseZone20                    = 189,
	MouseZone21                    = 190,
	MouseZone22                    = 191,
	HeadsetLeftZone                = 192,
	HeadsetRightZone               = 193,
	MousepadZone1                  = 194,
	MousepadZone2                  = 195,
	MousepadZone3                  = 196,
	MousepadZone4                  = 197,
	MousepadZone5                  = 198,
	MousepadZone6                  = 199,
	MousepadZone7                  = 200,
	MousepadZone8                  = 201,
	MousepadZone9                  = 202,
	MousepadZone10                 = 203,
	MousepadZone11                 = 204,
	MousepadZone12                 = 205,
	MousepadZone13                 = 206,
	MousepadZone14                 = 207,
	MousepadZone15                 = 208,
	HeadsetStandZone1              = 209,
	HeadsetStandZone2              = 210,
	HeadsetStandZone3              = 211,
	HeadsetStandZone4              = 212,
	HeadsetStandZone5              = 213,
	HeadsetStandZone6              = 214,
	HeadsetStandZone7              = 215,
	HeadsetStandZone8              = 216,
	HeadsetStandZone9              = 217,
	SpeakerLeft                    = 218,
	SpeakerRight                   = 219,
	MAX                            = 220,

};

// Enum Spectral.ESpectralDeviceType
enum class ESpectralDeviceType : uint8_t
{
	Keyboard                       = 0,
	Mouse                          = 1,
	Headset                        = 2,
	Mousepad                       = 3,
	HeadsetStand                   = 4,
	Speaker                        = 5,
	MAX                            = 6,

};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
